name: serialize_enum

description: Json serialization for Dart enumerations
  without source code generation.

version: 0.1.3

repository: https://github.com/simphotonics/serialize_enum

topics:
  - enum
  - json
  - serialization
  - persist

environment:
  sdk: ^3.8.0

dependencies:
  exception_templates: ^0.3.1
  lazy_memo: ^0.2.3

dev_dependencies:
  benchmark_runner: ^2.0.1
  lints: ^6.0.0
  test: ^1.26.2
